version: '3'
services:

  php:
    image: php:8.3-fpm
    build:
      context: ./
      dockerfile: docker/Dockerfile
    volumes:
      - './src:/var/www/html'
    links:
      - db


  nginx:
    image: nginx:latest
    ports:
      - '8082:80'
    volumes:
      - './src:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    links:
      - php

  db:
    image: postgres
    volumes:
    - './data:/var/lib/postgresql/data'
    ports:
      - '5434:5432'
    environment:
      POSTGRES_PASSWORD: "030201"
      POSTGRES_USER: "aryuna"
      POSTGRES_DB: "db"
