<body>
<div class="container">

    <h3><?php echo "Hello, {$_SESSION['user_name']}!"?></h3>

    <form action="/logout" method="POST">
        <button type="submit" class="buttons">Log Out</button>
    </form>

    <div class="cart-wrapper">
        <div class="cart-handle">
            <div class="cart-body">
                <div class="cart-hole1"></div>
                <div class="cart-hole2"></div>
                <a href="/cart"><span class="cart-items"><?php echo $this->countProducts($_SESSION['user_id']); ?></span></a>
            </div>
        </div>
    </div>

    <h3>Product Catalog</h3>

    <br>
    <div class="card-deck">
        <?php foreach ($products as $product) : ?>

            <div class="card text-center">
                <a href="#">
                    <img class="card-img-top" src="<?php echo $product->getImgUrl(); ?>" alt="Card image" width="250" height="190">
                    <div class="card-body">
                        <p class="card-text text-muted"><?php echo $product->getDescription(); ?></p>
                        <a href="#"><h5 class="card-title"><?php echo $product->getName(); ?></h5></a>
                        <div class="card-footer">
                            <?php echo $product->getPrice() . " руб."; ?>
                        </div>
                    </div>
                </a>

                <div id="controls">
                    <div> Количество: <span id="product-quantity-<?php echo $product->getId(); ?>"><?php echo $this->getProductQuantity($product, $_SESSION['user_id']); ?></span></div>

                    <form method="POST" onsubmit="return false" class="plusProductForm" data-product-id="<?php echo $product->getId(); ?>">
                        <input type="hidden" value="<?php echo $product->getId(); ?>" placeholder="Enter product id" name="product-id" id="product-id" required>
                        <input type="hidden" value="<?php echo $this->getProductQuantity($product, $_SESSION['user_id']); ?>" name="quantity" class="quantity" required>
                        <button type="submit" class="buttons">+</button>
                    </form>

                    <form method="POST" onsubmit="return false" class="minusProductForm" data-product-id="<?php echo $product->getId(); ?>">
                        <input type="hidden" value="<?php echo $product->getId(); ?>" placeholder="Enter product id" name="product-id" id="product-id" required>
                        <input type="hidden" value="<?php echo $this->getProductQuantity($product, $_SESSION['user_id']); ?>" name="quantity" class="quantity" required>
                        <button type="submit" class="buttons">-</button>
                    </form>
                </div>
            </div>
            <br>
            <br>

        <?php endforeach; ?>
    </div>
</div>
</body>

<script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
<script>
    $("document").ready(function() {
        $('.plusProductForm').on('click', function(event) {
            event.preventDefault();

            var currentQuantity = parseInt($('#product-quantity-' + $(this).data('product-id')).text());
            var newQuantity = currentQuantity + 1;
            var productId = $(this).data('product-id');
            $.ajax({
                type: "POST",
                url: "/product-plus",
                data: { 'product-id': productId },
                success: function() {
                    console.log('done');
                    $('#product-quantity-' + productId).text(newQuantity);
                    updateProductsCount(+1);
                }
            })
        });

        $('.minusProductForm').on('click', function(event) {
            event.preventDefault();

            var currentQuantity = parseInt($('#product-quantity-' + $(this).data('product-id')).text());
            var newQuantity = Math.max(currentQuantity - 1, 0);
            var productId = $(this).data('product-id');
            $.ajax({
                type: "POST",
                url: "/product-minus",
                data: { 'product-id': productId },
                success: function() {
                    console.log('done');
                    $('#product-quantity-' + productId).text(newQuantity);
                    updateProductsCount(-1);
                }
            })
        });
        function updateProductsCount(change) {
            var currentCount = parseInt($('.cart-items').text());
            var newCount = currentCount + change;
            $('.cart-items').text(newCount); // Обновление количества продуктов в корзине
        }
    });
</script>



<style>

    <style>
    body {
        font-style: sans-serif;
    }

    a {
        text-decoration: none;
    }

    a:hover {
        text-decoration: none;
    }

    h3 {
        line-height: 3em;
    }

    .card {
        max-width: 16rem;
    }

    .card:hover {
        box-shadow: 1px 2px 10px lightgray;
        transition: 0.2s;
    }

    .card-header {
        font-size: 13px;
        color: gray;
        background-color: white;
    }

    .text-muted {
        font-size: 11px;
    }

    .card-footer{
        font-weight: bold;
        font-size: 18px;
        background-color: white;
    }
    /*ЗДЕСЬ НАЧИНАЕТСЯ*/

    .cart-wrapper {
        display: block;
        height: 100px;
        width: 100px;
        margin: 0 auto;
        position: absolute;
        right: 100px;
        top: 20px;
    }

    .cart-body {
        display: block;
        height: 100px;
        width: 100px;
        background-color: grey;
        margin: 0 auto;
        position: relative;
        top: 30px;
        right: 20px;

        &:hover {
            background-color: red;
        }
    }

    .cart-handle {
        display: block;
        height: 60px;
        width: 60px;
        background-color: #fff;
        border: 6px solid grey;
        position: relative;
        bottom: 0px;
        border-radius: 60px;
        text-align: center;

        &:hover {
            border-color: red;
        }
    }

    .cart-hole1,
    .cart-hole2 {
        top: 10px;
        width: 6px;
        height: 6px;
        background-color: #fff;
        border-radius: 30px;
    }

    .cart-hole1 {
        position: absolute;
        left: 14px;
    }

    .cart-hole2 {
        position: absolute;
        right: 14px;
    }

    .cart-items {
        color: #fff;
        position: relative;
        top: 28px;
        font-family: Helvetica;
        font-weight: 600;
        font-size: 30px;
    }
</style>