<div class="container">

    <h3><?php echo "Hello, {$_SESSION['user_name']}!"?></h3>

    <div class="cart-wrapper">
        <div class="cart-handle">
            <div class="cart-body">
                <div class="cart-hole1"></div>
                <div class="cart-hole2"></div>
                <span class="cart-items">
        <a href="http://localhost:8082/cart"><?php echo $productsCount; ?></a>
      </span>
            </div>
        </div>
    </div>

    <h3>Product Catalog</h3>


<!--    <button id="plus">+1</button>-->

<!--    <div id="controls">-->
<!--        <p>Add to cart</p>-->
<!--        <button id="btnAdd" class="buttons">+</button>-->
<!--        <button id="btnRemove" class="buttons">-</button>-->
<!--    </div>-->


    <?php if (isset($errorsQuantity['quantity'])): ?>
        <label style="color: red"><?php echo $errorsQuantity['quantity']; ?></label>
    <?php endif; ?>
    <br>
    <br>
    <div class="card-deck">
        <?php foreach ($products as $product) : ?>
            <form action="/add-product" method="POST">
                <div class="card text-center">
                    <a href="#">
                        <div class="card-header">
                            Hit!
                        </div>
                        <img class="card-img-top" src="<?php echo $product['img_url']; ?>" alt="Card image"  width="250"
                             height="190">
                        <div class="card-body">
                            <p class="card-text text-muted"><?php echo $product['description']; ?></p>
                            <a href="#"><h5 class="card-title"><?php echo $product['name']; ?></h5></a>
                            <div class="card-footer">
                                <?php echo "{$product['price']} руб."; ?>
                            </div>
                        </div>
                    </a>
                    <input type="hidden" value="<?php echo "{$product['id']}"; ?>" placeholder="Enter product id" name="product-id" id="product-id" required>
                    <br>
                    <input type="text" placeholder="Enter quantity" name="quantity" id="quantity" required>
                    <br>
                    <button type="submit" class="registerbtn">Add products</button>
                </div>
                <br>
                <br>
            </form>
        <?php endforeach; ?>
    </div>
</div>
<style>
    body {
        font-style: sans-serif;
    }

    a {
        text-decoration: none;
    }

    a:hover {
        text-decoration: none;
    }

    h3 {
        line-height: 3em;
    }

    .card {
        max-width: 16rem;
    }

    .card:hover {
        box-shadow: 1px 2px 10px lightgray;
        transition: 0.2s;
    }

    .card-header {
        font-size: 13px;
        color: gray;
        background-color: white;
    }

    .text-muted {
        font-size: 11px;
    }

    .card-footer{
        font-weight: bold;
        font-size: 18px;
        background-color: white;
    }
    /*ЗДЕСЬ НАЧИНАЕТСЯ*/

    .cart-wrapper {
        display: block;
        height: 100px;
        width: 100px;
        margin: 0 auto;
        position: absolute;
        right: 100px;
        top: 20px;
    }

    .cart-body {
        display: block;
        height: 100px;
        width: 100px;
        background-color: grey;
        margin: 0 auto;
        position: relative;
        top: 30px;
        right: 20px;

        &:hover {
            background-color: red;
        }
    }

    .cart-handle {
        display: block;
        height: 60px;
        width: 60px;
        background-color: #fff;
        border: 6px solid grey;
        position: relative;
        bottom: 0px;
        border-radius: 60px;
        text-align: center;

        &:hover {
            border-color: red;
        }
    }

    .cart-hole1,
    .cart-hole2 {
        top: 10px;
        width: 6px;
        height: 6px;
        background-color: #fff;
        border-radius: 30px;
    }

    .cart-hole1 {
        position: absolute;
        left: 14px;
    }

    .cart-hole2 {
        position: absolute;
        right: 14px;
    }

    .cart-items {
        color: #fff;
        position: relative;
        top: 28px;
        font-family: Helvetica;
        font-weight: 600;
        font-size: 30px;
    }
</style>
