<link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,600,700,800" rel="stylesheet">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css">

<div class="orderpage">
    <div class="container">
        <div class="row">
            <div class="block_products col-12 col-md-12 col-sm-12 col-lg-12">
                <div class="title">Данные о платеже</div>
                <div class="product_parent">
                    <?php use Model\UserProduct;

                    if (empty($cart)) { ?>
                        <h2>It's empty here! Please add some products.</h2>
                    <?php } else {
                    foreach ($productsInfo as $productInfo) :?>
                    <div class="product">
                        <div class="image_product"><img src="<?php echo $productInfo->getImgUrl(); ?>" alt=""></div>
                        <div class="name_product"><?php echo $productInfo->getName(); ?><br /><span class="quantity"><?php echo UserProduct::getUserProductQuantity($productInfo->getId(), $user->getId()) . " шт."?></span></div>
                        <div class="price_product"><?php $total += $productInfo->getPrice() * UserProduct::getUserProductQuantity($productInfo->getId(), $user->getId());
                        echo $productInfo->getPrice() * UserProduct::getUserProductQuantity($productInfo->getId(), $user->getId()) . ' руб.';?></div>
                        <a href="#" class="close-btn"><i class="fas fa-times"></i></a>
                    </div>
                    <?php endforeach; } ?>
                </div>

                </div>
                <div class="total-price">
                    <span class="text">Итого к оплате:</span>
                    <span class="price"><?php echo $total; ?><sup> руб.</sup></span>
                </div>
            </div>

            <div class="block_contact col-12 col-md-12 col-sm-12 col-lg-12">
                <div class="title">Ваши контактные данные</div>
                <div class="input_block">

                    <label for="name_input"><i class="fas fa-user"></i> Имя и фамилия:</label>
                    <input id="name_input" type="text" required>
                </div>

                <div class="input_block">

                    <label for="phone_input"><i class="fas fa-phone"></i> Мобильный телефон:</label>
                    <input id="phone_input" type="text" required>
                </div>
                <div class="input_block">

                    <label for="email_input"><i class="fas fa-envelope"></i> Электронная почта:</label>
                    <input id="email_input" type="text" required>
                </div>
                <div class="input_block">

                    <label for="phone_input">Адрес доставки:</label>
                    <input id="phone_input" placeholder="Город и отделение новой почты" type="text" required>
                </div>
                <div class="payment_block">
                    <div class="method">Способ оплаты:</div>
                    <div class="check-f-i-field">
                        <input type="radio" id="vs/mc" name="payment" checked="" value="card" class="step2">
                        <label for="vs/mc"><span></span>Оплата картой Visa/MasterCard</label>
                    </div>

                </div>
                <div class="btn-block"><a href="#" class="btn-order">Заказ подтверждаю</a></div>
                <div class="specialist"><span class="mark">*</span> После оплаты с вами обязательно свяжется специалист для подтверждения заказа</div>
            </div>
            <div class="block_secure col-12 col-md-12 col-sm-12 col-lg-12">
                Конфиденциальная информация о номере Вашей карточки, CVV2 коде и другие ее реквизиты передаются на наш сайт в зашифрованном состоянии. Для обмена информацией с Вами применяется промышленный стандарт SSL-шифрования с использованием стойкой криптографии (длина ключа 128 бит). <br /><img src="https://prizolove.com/images/visa-secure.PNG">
                <img src="https://prizolove.com/images/mastercard.PNG">
                <img src="https://prizolove.com/images/pci-dss.png">
            </div>
        </div>
    </div>
</div>

<style>
    body{font-family:"Montserrat",arial,sans-serif;color:#333;font-weight:500;}
    *:focus{outline:none;}


    .orderpage{margin:30px 0;}
    .orderpage .container{max-width:768px;}


    /* ЗАГОЛОВОК */
    .orderpage .block_products .title,.orderpage .block_contact .title{font-size:18px;position:relative;padding-left:45px;font-weight:600;}
    .orderpage .block_products .title::before,.orderpage .block_contact .title::before{content:"";position:absolute;width:35px;height:15px;left:0;top:50%;
        transform:translateY(-50%);background:#4bbe3f;}


    /* БЛОК С ПЕРЕЧНЕМ ПРОДУКТОВ */
    .product_parent{margin-top:15px;background:#FCF3D0;border:1px solid #dbca9d;box-shadow:0px 3px 0px #dbca9d;border-radius:5px;padding:0px 15px 0px 15px;}
    .product{position:relative;padding:15px 0;border-bottom:1px solid #dbca9d;}
    .product:last-child{border-bottom:none;}
    .product div{display:inline-block;vertical-align:middle;}
    .product .image_product img{max-width:75px;width:100%;}
    .product .image_product{width:10%;overflow:hidden;}
    .product .name_product{width:69%;font-size:18px;line-height:21px;font-weight:500;color:#333;padding-left:20px;}
    .product .name_product .quantity{font-size:14px;opacity:0.6;}
    .product .price_product{width:19%;font-size:18px;font-weight:500;}
    .product .close-btn{position:absolute;right:10px;top:50%;margin-top:-12px;color:#333;transition:.5s;font-weight: bold;text-align:center;
        opacity:0.3;
        color: #333;
        width: 24px;
        height: 24px;
        font-size: 14px;
        line-height: 24px;
        border-radius: 50%;
        transition: 1s;
        z-index: 9999;
        cursor: pointer !important;}
    .product .close-btn:hover{opacity:1;background: #e74c3c;
        color: white;
        transform: rotate(360deg);}


    /* БЛОК ИТОГО К ОПЛАТЕ */
    .total-price{font-weight:500;margin:15px 15px 0 15px;font-size:18px;}
    .total-price .text{margin-right:20px;}
    .total-price .price{font-weight:bold;font-size:18px;color:#e74c3c;}


    /* БЛОК ВАШИ КОНТАКТНЫЕ ДАННЫЕ */
    .block_contact{margin:30px 0;}


    /* СТИЛИЗАЦИЯ ИНПУТОВ */
    .input_block{font-size:16px;color:#364A5D;margin:15px 15px 0 15px;}
    .input_block label{width:30%;line-height:22px;display:inline-block;vertical-align:middle;}
    .input_block label i{margin-right:7px;font-size:16px;}
    .input_block input{width:64%;display: inline-block;
        height: 34px;
        padding: 6px 12px;
        transition:.5s;
        font-size: 16px;
        font-weight:500;
        line-height: 1.428571429;
        color: #333;
        background-color: transparent;
        border: 1px solid #ccc;
        border-radius: 4px;
        -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,0.075);
        box-shadow: inset 0 1px 1px rgba(0,0,0,0.075);
    }
    .input_block input:focus{border-color: #66afe9;
        outline: 0;
        -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075), 0 0 8px rgba(102,175,233,0.6);
        box-shadow: inset 0 1px 1px rgba(0,0,0,.075), 0 0 8px rgba(102,175,233,0.6);}


    /* СТИЛИЗАЦИЯ СПОСОБА ОПЛАТЫ */
    .payment_block{margin:15px 15px 0px 15px;font-size:16px;}
    .payment_block .method{display:inline-block;width:30%;color:#364A5D;}
    .payment_block .check-f-i-field{display:inline-block;width:64%;color:black;}
    .check-f-i-field label{cursor:pointer;transition:.5s;position:relative;}
    .check-f-i-field label:hover{color:#e74c3c;}


    /* СТИЛИЗАЦИЯ КНОПКИ */
    .block_contact .btn-block{margin:15px 0 0 31%;text-align:left;}
    .block_contact .btn-order{font-size:16px;display:inline-block;color:white;vertical-align:middle;padding:7px 20px;font-weight:500;background: -webkit-linear-gradient(top,#79d670,#4bbe3f);box-shadow: 3px 3px 7px 0 rgba(105,206,95,.5), inset 0 -3px 0 0 #3a9731;    text-shadow: 0 -1px 0 rgba(0, 0, 0, .3);border-radius:5px;text-align:center;transition:.5s;border:none !important;cursor:pointer !Important;}
    .block_contact .btn-order:hover{text-decoration:none !important;background:-webkit-linear-gradient(top,#69f95b,#1fc80d);}


    /* БЛОК О СПЕЦИАЛИСТЕ */
    .block_contact .specialist{text-align:left;font-size:12px;margin: 5px 0px 0px 31%;color:#333;}
    .block_contact .specialist .mark{background:white;color:#e74c3c;}


    /* БЛОК СЕКЬЮРНОСТИ */
    .block_secure{font-size:10px;color:rgba(0,0,0,0.50);padding:30px 0 0 0;border-top:1px solid rgba(0,0,0,0.08);text-align:center;}
    .block_secure img{max-width:100px;}


    /* MEDIA ЗАПРОСЫ */
    @media screen and (max-width:750px){
        .input_block label{width:49%;}
        .input_block input{width:49%;}
        .payment_block .method{width:49%;}
        .payment_block .check-f-i-field{width:49%;}
        .block_contact .btn-block{margin:30px 0 0 0;text-align:center;}
        .block_contact .specialist{text-align:center;margin:5px 0px 0px 0px;padding:0 100px;}
        .total-price{margin:15px 0 0 0;}
        .total-price .text{margin-right:0px;}
        .input_block{margin:15px 0px 0 0px;}
        .payment_block{margin:30px 0px 0px 0px;}
    }

    @media screen and (max-width:690px){
        .product .close-btn{top:19%;}
    }

    @media screen and (max-width:628px){
        .input_block label{width:100%;}
        .input_block input{width:100%;}
        .payment_block .method{width:100%;}
        .payment_block .check-f-i-field{width:100%;}
        .block_contact .specialist{padding:0 0px;}
    }

    @media screen and (max-width:600px){
        .product .image_product{width:10%;}
        .product .name_product{width:58%;}
        .product .price_product{width:29%;text-align:right;}
    }

    @media screen and (max-width:470px){
        .product .image_product{width:29%;}
        .product .name_product{width:69%;}
        .product .price_product{width:100%;text-align:center;}
    }



    /* ЗЕЛЕНЫЙ БЛОК */


    .block_sertificate{
        font-weight:500;
        padding:10px;
        font-weight:500;
        font-size:16px;
        margin:20px 0 0 0;
        border-left:10px solid #8ac38b;
        border-color: #8ac38b;
        color: #356635;
        background: #CBDFC4;position:relative;}



    /* НОВЫЕ СТИЛИ */

    .input-wrapper input{background:white;border-top-left-radius:5px;border-bottom-left-radius:5px;border:1px solid #cece;font-size:14px;padding:5px 5px;display:inline-block;max-width:300px;vertical-align:middle;font-weight:500;}
    .input-wrapper button{background:#e74c3c;border:none;border-top-right-radius:5px;border-bottom-right-radius:5px;border:1px solid #e74c3c;font-size:14px;padding:5px 0px;display:inline-block;width:100px;text-align:center;vertical-align:middle;cursor:pointer;color:white;font-weight:500;}


</style>