<div id="container">
    <header>
        <div>
            <nav role="navigation">
                <ul>
                    <li><a href="/home">Home</a></li>
                    <li><a href="/main">Catalog</a></li>
                    <li><a href="/logout">Log Out</a></li>
                </ul>
            </nav>
        </div>
    </header>

    <br><br><br><br>

    <div id="content" role="main">
    {{content}}
    </div>

    <footer>
        <p id="copyright">&copy; Online-shop-aryuna</p>
    </footer>
</div>

<style>
    body, div, h1, h2, h3, h4, p, ul, li, a, img{
        margin: 0;
        padding: 0;
        border: 0;
    }

    body {
        font-family: Baskerville;
    }

    h1, h2, h3, h4, p{
        font-family: Bodoni;

    }

    img {
        width: 100%;
        height: 100%;
    }

    header {
        margin:0 0 0 0;
    }

    header img {
        width: 150px;
        margin-left: 10px;
    }

    header nav {
        float: right;
        text-align: right;
        padding: 30px 0 0 0;
    }

    header a {
        text-decoration: none;
    }

    header nav ul {
        list-style: none;
    }

    header nav li {
        float: left;
        font-size: 17px;
        width: 200px;
        margin: 10px 0 0 20px;
        text-align: center;
    }

    h2 {
        padding-left: 30px;
        font-weight: bold;
        text-align: center;
        padding-bottom: 50px;
    }

    #content {
        max-width: 960px;
        margin: 0 auto;
    }

    footer {
        margin-top: 50px;
        text-align: center;
        padding: 20px;
    }

    @media screen and (max-width: 785px) {
        #jewelry {
            flex-direction: column;
        }
        .product {
            width: 160px;
            font-size: 13px;
        }
        #sidebar .product {
            width: 120px;
        }
        #sidebar hr {
            display: none;
        }
    }

    @media screen and (max-width: 524px) {
        #jewelry {
            flex-direction: column;
        }
        .row {
            flex-direction: column;
        }
        .product {
            width: 350px;
        }
        #sidebar .product {
            width: 300px;
        }
        #sidebar hr {
            display: block;
        }
    }
</style>